#!/bin/bash
# Connect to vpn

function usage
{
    echo -e "Usage: " `basename "$0"`"\n"\
    "      " `basename "$0"` " -r\n"\
    "      " `basename "$0"` " -d\n\n"\
    `basename "$0"`"\t\tcreates initial vpn connection\n"\
    `basename "$0"`" -r\t\tcreates remmina connection\n"\
    `basename "$0"`" -d\t\tcloses vpn connection"
}

# Main

option=

while [ "$1" != "" ]; do
    case $1 in
	-r          )     option=$1
			  ;;
	-d          )     option=$1
	                  ;;
	-h | --help )     usage
			  exit
			  ;;
	* )               usage
			  exit 1
    esac
    shift
done

if [ "$option" = "-d" ]; then
    # Disconnect from vpn
    sudo ifconfig tun1 down
    sudo openvpn --rmtun --dev tun1
elif [ "$option" = "-r" ]; then
    # Make Remmina connection
    remmina -c $WORK_REMMINA_CONNECTION
else
    # Connect to vpn
    sudo openvpn --mktun --dev tun1
    sudo ifconfig tun1 up
    sudo openconnect $WORK_SERVER --authgroup=$WORK_GROUP --interface=tun1
fi
